# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: もょもと
subtitle: moyomoto
description: >- # this means to ignore newlines until "baseurl:"
    Here is ami-GS page, here should be include my profile and what I have learned.

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Daiki AMINAKA
email: 1991.daiki@gmail.com

# Social settings
facebook_url:
github_url: https://github.com/ami-GS
googleplus_url:
instagram_url:
linkedin_url: https://linkedin.com/in/daiki-aminaka
pinterest_url:
slack_url:
twitter_url: https://twitter.com/ami_GX

# Google Analytics Tracking ID goes here:
google_analytics: UA-49994041-3

# The following settings are NECESSARY for the Prologue theme to run:
theme: jekyll-theme-prologue
collections: [sections]

avatar: /assets/images/avatar.png

highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
gems:
  - rouge
